#########
## If you are using SSL to connect to EMS, make sure you also set the following:
##
## sslIdentityFile: path to the private key and client certificate file (example: conf/client_identity.p12)
## sslIdentityPassword: password to decrypt the private key
## sslTrustedCerts: path to the server certificate file (example: conf/server_cert.pem)
##########
servers:
   # Keep the display name blank if Tibco EMS Extension is monitoring only one Tibco Server.
   - displayName: "Local EMS"
     host: "192.168.1.11"
     port: "6222"
     # Supports tcp and ssl
     protocol: "tcp"
     #Add fault Tolerant servers
     faultTolerantServers: ["192.168.1.11:7222"]
     user: "admin"
     # password or encryptedPassword and encryptionKey are required
     password: "admin"
     encryptedPassword:
     encryptionKey:
    #We are going to  remove support for .* in next release. Other regex's are still supported.
     includeQueues: [".*"]
     includeTopics: [".*"]
     includeDurables: [".*"]
     includeRoutes: [".*"]
     includeProducers: [".*"]
     includeConsumers: [".*"]
     sslIdentityFile:
     sslIdentityPassword:
     sslIdentityEncryptedPassword:
     sslTrustedCerts:
     #ssl config optional settings
     sslDebug:
     sslVerifyHost:
     sslVerifyHostName:
     sslVendor:


# Each server instance needs 9 threads, one for the server instance itself, and others for collecting metrics from connection, consumer, durable, producer, queue, route, server and topic.
# So, please change the value accordingly(Based on the number of server instances you are monitoring).
numberOfThreads: 15

#This will create this metric in all the tiers, under this path. Please make sure to have a trailing |
#metricPrefix: "Custom Metrics|Tibco EMS|"

#This will create it in specific Tier aka Component. Replace <COMPONENT_ID>. Please make sure to have a trailing |.
#To find out the COMPONENT_ID, please see the screen shot here https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Tibco EMS|"